---
  swagger: "2.0"
  info:
    title: Lootdrop API
    description: Lootdrop Service Definition
    termsOfService: http://lootdrop.io/terms/
    contact:
      name: Lootdrop Support
      url: http://www.lootdrop.io/support
      email: support@lootdrop.io
  host: "www.lootdrop.io"
  basepath: "api/v1"
  schemes:
    - "http"
  consumes:
    - "application/json"
  produces:
    - "application/json"
  paths:
    /greeting:
      get:
        description: "Starts signup subscription process"
        operationId: "getGreeting"
        produces:
          - "application/json"
        responses:
          "200":
            description: "greeting response"
            schema: "#/definitions/Greeting"
          "default":
            description: "unexpected error"
